//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public long ContractId { get; set; }
        public Nullable<long> AddressId { get; set; }
        public Nullable<long> ServiceTypeXRefId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> RemainingBalance { get; set; }
    }
}
