//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenPO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equation
    {
        public long Id { get; set; }
        public string equation1 { get; set; }
        public string queueid { get; set; }
        public string evaluated { get; set; }
        public string cellname { get; set; }
    }
}
